// 10 Prebuilt Certificate Templates with Professional Designs
export const PREBUILT_TEMPLATES = [
  {
    id: 1,
    name: 'Classic Gold',
    description: 'Elegant gold and white classic design',
    preview: '🏆',
    template: {
      heading: 'Certificate of Achievement',
      headingColor: '#1a472a',
      headingFontSize: 52,
      subHeading: 'This is to certify that',
      subHeadingFontSize: 22,
      descriptionText: 'has successfully completed the course and demonstrated exceptional commitment to learning',
      descriptionFontSize: 18,
      descriptionColor: '#333333',
      recipientNameFontSize: 40,
      recipientNameColor: '#d4af37',
      organizerName: 'Event Organizer',
      backgroundColor: '#f5f5f5',
      accentColor: '#d4af37',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#666666',
      borderStyle: 'elegant',
      borderColor: '#d4af37',
      templateDesign: 'landscape',
      bgPattern: 'diagonal-lines',
    },
  },
  {
    id: 2,
    name: 'Modern Blue',
    description: 'Contemporary blue gradient design',
    preview: '🔵',
    template: {
      heading: 'Certificate of Completion',
      headingColor: '#ffffff',
      headingFontSize: 48,
      subHeading: 'Presented to',
      subHeadingFontSize: 20,
      descriptionText: 'for outstanding performance and dedication',
      descriptionFontSize: 18,
      descriptionColor: '#ffffff',
      recipientNameFontSize: 38,
      recipientNameColor: '#ffffff',
      organizerName: 'Event Organizer',
      backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      accentColor: '#ffffff',
      footerText: 'Issued on {date}',
      footerFontSize: 14,
      footerColor: '#ffffff',
      borderStyle: 'modern',
      borderColor: '#ffffff',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 3,
    name: 'Minimalist',
    description: 'Clean and simple minimalist design',
    preview: '⚪',
    template: {
      heading: 'Certificate',
      headingColor: '#000000',
      headingFontSize: 44,
      subHeading: 'OF RECOGNITION',
      subHeadingFontSize: 18,
      descriptionText: 'This certifies that the bearer has successfully participated in',
      descriptionFontSize: 16,
      descriptionColor: '#333333',
      recipientNameFontSize: 36,
      recipientNameColor: '#000000',
      organizerName: 'Issued By',
      backgroundColor: '#ffffff',
      accentColor: '#000000',
      footerText: '{date}',
      footerFontSize: 12,
      footerColor: '#666666',
      borderStyle: 'simple',
      borderColor: '#000000',
      templateDesign: 'portrait',
      bgPattern: 'none',
    },
  },
  {
    id: 4,
    name: 'Sunset Glow',
    description: 'Warm orange and red sunset gradient',
    preview: '🌅',
    template: {
      heading: 'Certificate of Excellence',
      headingColor: '#ffffff',
      headingFontSize: 50,
      subHeading: 'Proudly Presented To',
      subHeadingFontSize: 22,
      descriptionText: 'In recognition of outstanding achievements and dedication',
      descriptionFontSize: 18,
      descriptionColor: '#ffffff',
      recipientNameFontSize: 40,
      recipientNameColor: '#ffe6cc',
      organizerName: 'Event Organizer',
      backgroundColor: 'linear-gradient(135deg, #ff6b6b 0%, #ff8c3a 50%, #ffd93d 100%)',
      accentColor: '#ffe6cc',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#ffffff',
      borderStyle: 'elegant',
      borderColor: '#ffe6cc',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 5,
    name: 'Forest Green',
    description: 'Natural green with organic elements',
    preview: '🌿',
    template: {
      heading: 'Certificate of Completion',
      headingColor: '#1b4332',
      headingFontSize: 48,
      subHeading: 'This honors',
      subHeadingFontSize: 20,
      descriptionText: 'for successfully completing the program and demonstrating excellence',
      descriptionFontSize: 18,
      descriptionColor: '#2d6a4f',
      recipientNameFontSize: 38,
      recipientNameColor: '#1b4332',
      organizerName: 'Event Organizer',
      backgroundColor: '#d8f3dc',
      accentColor: '#52b788',
      footerText: 'Issued: {date}',
      footerFontSize: 14,
      footerColor: '#40916c',
      borderStyle: 'elegant',
      borderColor: '#52b788',
      templateDesign: 'landscape',
      bgPattern: 'leaf-pattern',
    },
  },
  {
    id: 6,
    name: 'Royal Purple',
    description: 'Regal purple and gold combination',
    preview: '👑',
    template: {
      heading: 'Certificate of Honor',
      headingColor: '#4a148c',
      headingFontSize: 50,
      subHeading: 'Awarded To',
      subHeadingFontSize: 22,
      descriptionText: 'In recognition of exceptional service and outstanding contribution',
      descriptionFontSize: 18,
      descriptionColor: '#6a1b9a',
      recipientNameFontSize: 40,
      recipientNameColor: '#c71585',
      organizerName: 'Event Organizer',
      backgroundColor: '#f3e5f5',
      accentColor: '#9c27b0',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#6a1b9a',
      borderStyle: 'elegant',
      borderColor: '#d4a5ff',
      templateDesign: 'landscape',
      bgPattern: 'ornamental',
    },
  },
  {
    id: 7,
    name: 'Ocean Breeze',
    description: 'Cool ocean blue and cyan colors',
    preview: '🌊',
    template: {
      heading: 'Certificate of Achievement',
      headingColor: '#004d6d',
      headingFontSize: 48,
      subHeading: 'Presented To',
      subHeadingFontSize: 20,
      descriptionText: 'for excellence and outstanding performance',
      descriptionFontSize: 18,
      descriptionColor: '#004d6d',
      recipientNameFontSize: 38,
      recipientNameColor: '#0097a7',
      organizerName: 'Event Organizer',
      backgroundColor: '#e0f7ff',
      accentColor: '#00bcd4',
      footerText: '{date}',
      footerFontSize: 14,
      footerColor: '#004d6d',
      borderStyle: 'modern',
      borderColor: '#0097a7',
      templateDesign: 'portrait',
      bgPattern: 'wave',
    },
  },
  {
    id: 8,
    name: 'Midnight Star',
    description: 'Dark elegant with silver accents',
    preview: '⭐',
    template: {
      heading: 'Certificate of Excellence',
      headingColor: '#e8eaed',
      headingFontSize: 50,
      subHeading: 'Is Proudly Awarded To',
      subHeadingFontSize: 22,
      descriptionText: 'For exceptional dedication and outstanding achievements',
      descriptionFontSize: 18,
      descriptionColor: '#bdc3c7',
      recipientNameFontSize: 40,
      recipientNameColor: '#f1c40f',
      organizerName: 'Event Organizer',
      backgroundColor: '#1a1a2e',
      accentColor: '#f1c40f',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#95a5a6',
      borderStyle: 'elegant',
      borderColor: '#f1c40f',
      templateDesign: 'landscape',
      bgPattern: 'stars',
    },
  },
  {
    id: 9,
    name: 'Coral Sunset',
    description: 'Warm coral and peachy tones',
    preview: '🪸',
    template: {
      heading: 'Certificate of Recognition',
      headingColor: '#ffffff',
      headingFontSize: 48,
      subHeading: 'Honoring',
      subHeadingFontSize: 20,
      descriptionText: 'For outstanding contribution and successful completion',
      descriptionFontSize: 18,
      descriptionColor: '#ffffff',
      recipientNameFontSize: 38,
      recipientNameColor: '#ffe0e0',
      organizerName: 'Event Organizer',
      backgroundColor: 'linear-gradient(135deg, #f97c7c 0%, #ffa07a 50%, #ffb6a3 100%)',
      accentColor: '#ffe0e0',
      footerText: 'Issued on {date}',
      footerFontSize: 14,
      footerColor: '#ffffff',
      borderStyle: 'elegant',
      borderColor: '#ffe0e0',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 10,
    name: 'Corporate Slate',
    description: 'Professional corporate design',
    preview: '🏢',
    template: {
      heading: 'CERTIFICATE OF COMPLETION',
      headingColor: '#1f3a5f',
      headingFontSize: 46,
      subHeading: 'This certifies that',
      subHeadingFontSize: 18,
      descriptionText: 'has successfully completed and passed all requirements',
      descriptionFontSize: 16,
      descriptionColor: '#3d5a80',
      recipientNameFontSize: 36,
      recipientNameColor: '#1f3a5f',
      organizerName: 'Event Organizer',
      backgroundColor: '#ecf0f5',
      accentColor: '#2c5aa0',
      footerText: '{date}',
      footerFontSize: 13,
      footerColor: '#5a7a96',
      borderStyle: 'simple',
      borderColor: '#2c5aa0',
      templateDesign: 'landscape',
      bgPattern: 'none',
    },
  },
];

export const getTemplateById = (id) => {
  const tmpl = PREBUILT_TEMPLATES.find((t) => t.id === id);
  return tmpl ? { ...tmpl.template } : null;
};
