// 15+ Prebuilt Certificate Templates with Professional Designs
export const PREBUILT_TEMPLATES = [
  {
    id: 101,
    previewVariant: 1,
    name: 'Blue Gold Appreciation',
    description: 'Minimal white certificate with refined navy and gold accents',
    template: {
      heading: 'CERTIFICATE OF APPRECIATION',
      headingColor: '#102a43',
      headingFontSize: 42,
      subHeading: 'This certificate is presented to',
      subHeadingFontSize: 16,
      descriptionText: 'In recognition of excellence, dedication, and outstanding contribution.',
      descriptionFontSize: 14,
      descriptionColor: '#334e68',
      recipientNameFontSize: 40,
      recipientNameColor: '#b68f40',
      recipientNameFontFamily: 'Great Vibes, cursive',
      organizerName: 'EventGlow',
      backgroundColor: '#ffffff',
      accentColor: '#b68f40',
      footerText: 'Date: {date}',
      footerFontSize: 12,
      footerColor: '#627d98',
      borderStyle: 'simple',
      borderColor: '#102a43',
      templateDesign: 'landscape',
    },
  },
  {
    id: 102,
    previewVariant: 2,
    name: 'Black Gold Luxury',
    description: 'Dark premium certificate with gold ribbons and glowing accents',
    template: {
      heading: 'CERTIFICATE OF ACHIEVEMENT',
      headingColor: '#f8e9a1',
      headingFontSize: 42,
      subHeading: 'Awarded to',
      subHeadingFontSize: 16,
      descriptionText: 'For exceptional performance and distinguished contribution.',
      descriptionFontSize: 14,
      descriptionColor: '#f3e5a9',
      recipientNameFontSize: 40,
      recipientNameColor: '#f8e9a1',
      recipientNameFontFamily: 'Playfair Display, serif',
      organizerName: 'EventGlow',
      backgroundColor: '#10121a',
      accentColor: '#d4af37',
      footerText: 'Issued: {date}',
      footerFontSize: 12,
      footerColor: '#bfb18b',
      borderStyle: 'thick',
      borderColor: '#d4af37',
      templateDesign: 'landscape',
    },
  },
  {
    id: 103,
    previewVariant: 3,
    name: 'Green Academic Honor',
    description: 'University-style certificates with geometric green side panels',
    template: {
      heading: 'CERTIFICATE OF APPRECIATION',
      headingColor: '#124b30',
      headingFontSize: 40,
      subHeading: 'Presented to',
      subHeadingFontSize: 15,
      descriptionText: 'In recognition of academic excellence and outstanding achievement.',
      descriptionFontSize: 14,
      descriptionColor: '#2d6a4f',
      recipientNameFontSize: 38,
      recipientNameColor: '#10665b',
      recipientNameFontFamily: 'Georgia, serif',
      organizerName: 'EventGlow',
      backgroundColor: '#ffffff',
      accentColor: '#10665b',
      footerText: 'Date: {date}',
      footerFontSize: 12,
      footerColor: '#617d72',
      borderStyle: 'simple',
      borderColor: '#10665b',
      templateDesign: 'landscape',
    },
  },
  {
    id: 104,
    previewVariant: 4,
    name: 'Ivory Floral Classic',
    description: 'Classic ivory certificate with vintage floral corners and wax seal',
    template: {
      heading: 'CERTIFICATE OF ACHIEVEMENT',
      headingColor: '#4a1f1f',
      headingFontSize: 42,
      subHeading: 'This certifies that',
      subHeadingFontSize: 15,
      descriptionText: 'Has demonstrated remarkable dedication and academic excellence.',
      descriptionFontSize: 14,
      descriptionColor: '#5e3a31',
      recipientNameFontSize: 38,
      recipientNameColor: '#7a2d2d',
      recipientNameFontFamily: 'Merriweather, serif',
      organizerName: 'EventGlow',
      backgroundColor: '#fcf5eb',
      accentColor: '#7a2d2d',
      footerText: 'Date: {date}',
      footerFontSize: 12,
      footerColor: '#6c574b',
      borderStyle: 'elegant',
      borderColor: '#7a2d2d',
      templateDesign: 'landscape',
    },
  },
  {
    id: 105,
    previewVariant: 5,
    name: 'Maroon Gold Creative',
    description: 'Bold maroon certificate with diagonal gold accents and ribbon medal',
    template: {
      heading: 'CERTIFICATE OF APPRECIATION',
      headingColor: '#ffffff',
      headingFontSize: 40,
      subHeading: 'Presented to',
      subHeadingFontSize: 16,
      descriptionText: 'For creative excellence and remarkable achievement.',
      descriptionFontSize: 14,
      descriptionColor: '#f7f2ea',
      recipientNameFontSize: 38,
      recipientNameColor: '#ffd97d',
      recipientNameFontFamily: 'Cormorant Garamond, serif',
      organizerName: 'EventGlow',
      backgroundColor: '#5a1a1a',
      accentColor: '#d4af37',
      footerText: 'Issued on {date}',
      footerFontSize: 12,
      footerColor: '#f0e1c6',
      borderStyle: 'double',
      borderColor: '#d4af37',
      templateDesign: 'landscape',
    },
  },
  {
    id: 106,
    previewVariant: 6,
    name: 'Luxury Gold Prestige',
    description: 'Premium cream certificate with gold overlays and wreath accent',
    template: {
      heading: 'CERTIFICATE OF APPRECIATION',
      headingColor: '#4c3a1f',
      headingFontSize: 42,
      subHeading: 'Presented to',
      subHeadingFontSize: 16,
      descriptionText: 'For exceptional leadership and outstanding performance.',
      descriptionFontSize: 14,
      descriptionColor: '#6a5c45',
      recipientNameFontSize: 38,
      recipientNameColor: '#a17d3d',
      recipientNameFontFamily: 'Playfair Display, serif',
      organizerName: 'EventGlow',
      backgroundColor: '#fbf5eb',
      accentColor: '#b38d4d',
      footerText: 'Date: {date}',
      footerFontSize: 12,
      footerColor: '#7a6a52',
      borderStyle: 'elegant',
      borderColor: '#b38d4d',
      templateDesign: 'landscape',
    },
  },
  {
    id: 107,
    previewVariant: 7,
    name: 'Purple Minimal Modern',
    description: 'Minimal white certificate with purple accents and thin outline',
    template: {
      heading: 'CERTIFICATE OF ACHIEVEMENT',
      headingColor: '#2e1065',
      headingFontSize: 40,
      subHeading: 'Awarded to',
      subHeadingFontSize: 15,
      descriptionText: 'For outstanding contribution and modern excellence.',
      descriptionFontSize: 14,
      descriptionColor: '#3f2a72',
      recipientNameFontSize: 38,
      recipientNameColor: '#5b3db6',
      recipientNameFontFamily: 'Inter, sans-serif',
      organizerName: 'EventGlow',
      backgroundColor: '#ffffff',
      accentColor: '#5b3db6',
      footerText: 'Date: {date}',
      footerFontSize: 12,
      footerColor: '#6562a6',
      borderStyle: 'simple',
      borderColor: '#5b3db6',
      templateDesign: 'landscape',
    },
  },
  {
    id: 108,

    
    previewVariant: 8,
    name: 'Blue Gold Wave',
    description: 'Elegant blue certificate with flowing abstract waves and embossed seal',
    template: {
      heading: 'CERTIFICATE OF APPRECIATION',
      headingColor: '#0b3d91',
      headingFontSize: 42,
      subHeading: 'Awarded to',
      subHeadingFontSize: 16,
      descriptionText: 'In recognition of remarkable achievement and premium design excellence.',
      descriptionFontSize: 14,
      descriptionColor: '#27427c',
      recipientNameFontSize: 38,
      recipientNameColor: '#c9a54b',
      recipientNameFontFamily: 'Georgia, serif',
      organizerName: 'EventGlow',
      backgroundColor: '#eef4fb',
      accentColor: '#c9a54b',
      footerText: 'Issued: {date}',
      footerFontSize: 12,
      footerColor: '#5a6d8b',
      borderStyle: 'simple',
      borderColor: '#0b3d91',
      templateDesign: 'landscape',
    },
  },
  {
    id: 1,
    name: 'Classic Gold',
    description: 'Elegant gold and white classic design',
    preview: '🏆',
    template: {
      heading: 'Certificate of Achievement',
      headingColor: '#1a472a',
      headingFontSize: 52,
      subHeading: 'This is to certify that',
      subHeadingFontSize: 22,
      descriptionText: 'has successfully completed the course and demonstrated exceptional commitment to learning',
      descriptionFontSize: 18,
      descriptionColor: '#333333',
      recipientNameFontSize: 40,
      recipientNameColor: '#d4af37',
      organizerName: 'EventGlow',
      backgroundColor: '#f5f5f5',
      accentColor: '#d4af37',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#666666',
      borderStyle: 'elegant',
      borderColor: '#d4af37',
      templateDesign: 'landscape',
      bgPattern: 'diagonal-lines',
    },
        },
  {
    id: 2,
    name: 'Modern Blue',
    description: 'Contemporary blue gradient design',
    preview: '🔵',
    template: {
      heading: 'Certificate of Completion',
      headingColor: '#ffffff',
      headingFontSize: 48,
      subHeading: 'Presented to',
      subHeadingFontSize: 20,
      descriptionText: 'for outstanding performance and dedication',
      descriptionFontSize: 18,
      descriptionColor: '#ffffff',
      recipientNameFontSize: 38,
      recipientNameColor: '#ffffff',
      organizerName: 'EventGlow',
      backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      accentColor: '#ffffff',
      footerText: 'Issued on {date}',
      footerFontSize: 14,
      footerColor: '#ffffff',
      borderStyle: 'modern',
      borderColor: '#ffffff',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 3,
    name: 'Minimalist',
    description: 'Clean and simple minimalist design',
    preview: '⚪',
    template: {
      heading: 'Certificate',
      headingColor: '#000000',
      headingFontSize: 44,
      subHeading: 'OF RECOGNITION',
      subHeadingFontSize: 18,
      descriptionText: 'This certifies that the bearer has successfully participated in',
      descriptionFontSize: 16,
      descriptionColor: '#333333',
      recipientNameFontSize: 36,
      recipientNameColor: '#000000',
      organizerName: 'EventGlow',
      backgroundColor: '#ffffff',
      accentColor: '#000000',
      footerText: '{date}',
      footerFontSize: 12,
      footerColor: '#666666',
      borderStyle: 'simple',
      borderColor: '#000000',
      templateDesign: 'portrait',
      bgPattern: 'none',
    },
  },
  {
    id: 4,
    name: 'Sunset Glow',
    description: 'Warm orange and red sunset gradient',
    preview: '🌅',
    template: {
      heading: 'Certificate of Excellence',
      headingColor: '#ffffff',
      headingFontSize: 50,
      subHeading: 'Proudly Presented To',
      subHeadingFontSize: 22,
      descriptionText: 'In recognition of outstanding achievements and dedication',
      descriptionFontSize: 18,
      descriptionColor: '#ffffff',
      recipientNameFontSize: 40,
      recipientNameColor: '#ffe6cc',
      organizerName: 'EventGlow',
      backgroundColor: 'linear-gradient(135deg, #ff6b6b 0%, #ff8c3a 50%, #ffd93d 100%)',
      accentColor: '#ffe6cc',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#ffffff',
      borderStyle: 'elegant',
      borderColor: '#ffe6cc',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 5,
    name: 'Forest Green',
    description: 'Natural green with organic elements',
    preview: '🌿',
    template: {
      heading: 'Certificate of Completion',
      headingColor: '#1b4332',
      headingFontSize: 48,
      subHeading: 'This honors',
      subHeadingFontSize: 20,
      descriptionText: 'for successfully completing the program and demonstrating excellence',
      descriptionFontSize: 18,
      descriptionColor: '#2d6a4f',
      recipientNameFontSize: 38,
      recipientNameColor: '#1b4332',
      organizerName: 'EventGlow',
      backgroundColor: '#d8f3dc',
      accentColor: '#52b788',
      footerText: 'Issued: {date}',
      footerFontSize: 14,
      footerColor: '#40916c',
      borderStyle: 'elegant',
      borderColor: '#52b788',
      templateDesign: 'landscape',
      bgPattern: 'leaf-pattern',
    },
  },
  {
    id: 6,
    name: 'Royal Purple',
    description: 'Regal purple and gold combination',
    preview: '👑',
    template: {
      heading: 'Certificate of Honor',
      headingColor: '#4a148c',
      headingFontSize: 50,
      subHeading: 'Awarded To',
      subHeadingFontSize: 22,
      descriptionText: 'In recognition of exceptional service and outstanding contribution',
      descriptionFontSize: 18,
      descriptionColor: '#6a1b9a',
      recipientNameFontSize: 40,
      recipientNameColor: '#c71585',
      organizerName: 'EventGlow',
      backgroundColor: '#f3e5f5',
      accentColor: '#9c27b0',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#6a1b9a',
      borderStyle: 'elegant',
      borderColor: '#d4a5ff',
      templateDesign: 'landscape',
      bgPattern: 'ornamental',
    },
  },
  {
    id: 7,
    name: 'Ocean Breeze',
    description: 'Cool ocean blue and cyan colors',
    preview: '🌊',
    template: {
      heading: 'Certificate of Achievement',
      headingColor: '#004d6d',
      headingFontSize: 48,
      subHeading: 'Presented To',
      subHeadingFontSize: 20,
      descriptionText: 'for excellence and outstanding performance',
      descriptionFontSize: 18,
      descriptionColor: '#004d6d',
      recipientNameFontSize: 38,
      recipientNameColor: '#0097a7',
      organizerName: 'EventGlow',
      backgroundColor: '#e0f7ff',
      accentColor: '#00bcd4',
      footerText: '{date}',
      footerFontSize: 14,
      footerColor: '#004d6d',
      borderStyle: 'modern',
      borderColor: '#0097a7',
      templateDesign: 'portrait',
      bgPattern: 'wave',
    },
  },
  {
    id: 8,
    name: 'Midnight Star',
    description: 'Dark elegant with silver accents',
    preview: '⭐',
    template: {
      heading: 'Certificate of Excellence',
      headingColor: '#e8eaed',
      headingFontSize: 50,
      subHeading: 'Is Proudly Awarded To',
      subHeadingFontSize: 22,
      descriptionText: 'For exceptional dedication and outstanding achievements',
      descriptionFontSize: 18,
      descriptionColor: '#bdc3c7',
      recipientNameFontSize: 40,
      recipientNameColor: '#f1c40f',
      organizerName: 'EventGlow',
      backgroundColor: '#1a1a2e',
      accentColor: '#f1c40f',
      footerText: 'Date: {date}',
      footerFontSize: 14,
      footerColor: '#95a5a6',
      borderStyle: 'elegant',
      borderColor: '#f1c40f',
      templateDesign: 'landscape',
      bgPattern: 'stars',
    },
  },
  {
    id: 9,
    name: 'Coral Sunset',
    description: 'Warm coral and peachy tones',
    preview: '🪸',
    template: {
      heading: 'Certificate of Recognition',
      headingColor: '#ffffff',
      headingFontSize: 48,
      subHeading: 'Honoring',
      subHeadingFontSize: 20,
      descriptionText: 'For outstanding contribution and successful completion',
      descriptionFontSize: 18,
      descriptionColor: '#ffffff',
      recipientNameFontSize: 38,
      recipientNameColor: '#ffe0e0',
      organizerName: 'EventGlow',
      backgroundColor: 'linear-gradient(135deg, #f97c7c 0%, #ffa07a 50%, #ffb6a3 100%)',
      accentColor: '#ffe0e0',
      footerText: 'Issued on {date}',
      footerFontSize: 14,
      footerColor: '#ffffff',
      borderStyle: 'elegant',
      borderColor: '#ffe0e0',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 10,
    name: 'Corporate Slate',
    description: 'Professional corporate design',
    preview: '🏢',
    template: {
      heading: 'CERTIFICATE OF COMPLETION',
      headingColor: '#1f3a5f',
      headingFontSize: 46,
      subHeading: 'This certifies that',
      subHeadingFontSize: 18,
      descriptionText: 'has successfully completed and passed all requirements',
      descriptionFontSize: 16,
      descriptionColor: '#3d5a80',
      recipientNameFontSize: 36,
      recipientNameColor: '#1f3a5f',
      organizerName: 'EventGlow',
      backgroundColor: '#ecf0f5',
      accentColor: '#2c5aa0',
      footerText: '{date}',
      footerFontSize: 13,
      footerColor: '#5a7a96',
      borderStyle: 'simple',
      borderColor: '#2c5aa0',
      templateDesign: 'landscape',
      bgPattern: 'none',
    },
  },
  {
    id: 11,
    name: 'Emerald Prestige',
    description: 'Premium emerald and gold',
    preview: '💎',
    template: {
      heading: 'Certificate of Prestige',
      headingColor: '#1a4d3e',
      headingFontSize: 52,
      subHeading: 'Presented With Pride To',
      subHeadingFontSize: 22,
      descriptionText: 'For excellence and outstanding achievement',
      descriptionFontSize: 18,
      descriptionColor: '#2a7f5c',
      recipientNameFontSize: 42,
      recipientNameColor: '#d4a574',
      organizerName: 'EventGlow',
      backgroundColor: 'linear-gradient(135deg, #0f3d1f 0%, #1a6b3f 100%)',
      accentColor: '#d4a574',
      footerText: '{date}',
      footerFontSize: 14,
      footerColor: '#e8d5c0',
      borderStyle: 'elegant',
      borderColor: '#d4a574',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 12,
    name: 'Tech Innovation',
    description: 'Modern tech-style gradient',
    preview: '🚀',
    template: {
      heading: 'CERTIFICATE OF ACHIEVEMENT',
      headingColor: '#00d4ff',
      headingFontSize: 48,
      subHeading: 'Presented to',
      subHeadingFontSize: 20,
      descriptionText: 'For innovation and technical excellence',
      descriptionFontSize: 17,
      descriptionColor: '#e0e0e0',
      recipientNameFontSize: 40,
      recipientNameColor: '#00ff88',
      organizerName: 'EventGlow',
      backgroundColor: 'linear-gradient(135deg, #0a0e27 0%, #1a1a4d 50%, #2d0052 100%)',
      accentColor: '#00ff88',
      footerText: '{date}',
      footerFontSize: 14,
      footerColor: '#00d4ff',
      borderStyle: 'modern',
      borderColor: '#00ff88',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 13,
    name: 'Rose Gold Elegance',
    description: 'Sophisticated rose gold',
    preview: '✨',
    template: {
      heading: 'Certificate of Excellence',
      headingColor: '#6b4423',
      headingFontSize: 50,
      subHeading: 'Is Awarded To',
      subHeadingFontSize: 22,
      descriptionText: 'For extraordinary commitment and achievement',
      descriptionFontSize: 18,
      descriptionColor: '#8b5a3c',
      recipientNameFontSize: 40,
      recipientNameColor: '#b76e79',
      organizerName: 'EventGlow',
      backgroundColor: '#fdf8f6',
      accentColor: '#b76e79',
      footerText: '{date}',
      footerFontSize: 14,
      footerColor: '#9b6b7d',
      borderStyle: 'elegant',
      borderColor: '#d4a5ad',
      templateDesign: 'landscape',
      bgPattern: 'none',
    },
  },
  {
    id: 14,
    name: 'Vibrant Energy',
    description: 'Bold vibrant colors',
    preview: '⚡',
    template: {
      heading: 'CERTIFICATE OF ACHIEVEMENT',
      headingColor: '#ffffff',
      headingFontSize: 50,
      subHeading: 'Proudly Awarded to',
      subHeadingFontSize: 22,
      descriptionText: 'For exceptional performance and dedication',
      descriptionFontSize: 18,
      descriptionColor: '#ffffff',
      recipientNameFontSize: 40,
      recipientNameColor: '#ffff00',
      organizerName: 'EventGlow',
      backgroundColor: 'linear-gradient(135deg, #e74c3c 0%, #e67e22 50%, #2ecc71 100%)',
      accentColor: '#ffff00',
      footerText: '{date}',
      footerFontSize: 14,
      footerColor: '#ffffff',
      borderStyle: 'modern',
      borderColor: '#ffff00',
      templateDesign: 'landscape',
      bgPattern: 'gradient',
    },
  },
  {
    id: 15,
    name: 'Zen Harmony',
    description: 'Peaceful minimal zen design',
    preview: '🧘',
    template: {
      heading: 'Certificate',
      headingColor: '#333333',
      headingFontSize: 44,
      subHeading: 'of Completion',
      subHeadingFontSize: 18,
      descriptionText: 'Awarded in recognition of achievement',
      descriptionFontSize: 16,
      descriptionColor: '#666666',
      recipientNameFontSize: 36,
      recipientNameColor: '#5c9d7c',
      organizerName: 'EventGlow',
      backgroundColor: '#f5f5f1',
      accentColor: '#5c9d7c',
      footerText: '{date}',
      footerFontSize: 12,
      footerColor: '#999999',
      borderStyle: 'simple',
      borderColor: '#d0d0c8',
      templateDesign: 'portrait',
      bgPattern: 'none',
    },
  },
];

export const getTemplateById = (id) => {
  const tmpl = PREBUILT_TEMPLATES.find((t) => t.id === id);
  return tmpl ? { ...tmpl.template } : null;
};

export const getTemplateWithDecorations = (id) => {
  const tmpl = PREBUILT_TEMPLATES.find((t) => t.id === id);
  if (!tmpl) return null;
  
  return {
    id: tmpl.id,
    name: tmpl.name,
    description: tmpl.description,
    previewVariant: tmpl.previewVariant || null,
    template: {
      ...tmpl.template,
      previewVariant: tmpl.previewVariant || null,
    },
  };
};

export const getAllTemplatesWithDecorations = () => {
  return PREBUILT_TEMPLATES.map((tmpl) => ({
    id: tmpl.id,
    name: tmpl.name,
    description: tmpl.description,
    previewVariant: tmpl.previewVariant || null,
    template: {
      ...tmpl.template,
      previewVariant: tmpl.previewVariant || null,
    },
  }));
};
